---
title: Base repository for reusable Viash components
format: gfm
---

This repository is a collection of reproducible and reusable Viash components.

## Objectives

- **Reusability**: Facilitating the use of components across various projects and contexts.
- **Reproducibility**: Guaranteeing that bioinformatics analyses can be reliably replicated.
- **Best Practices**: Adhering to established standards in software development and bioinformatics.

## Contributing

We encourage contributions from the community. To contribute:

1. **Fork the Repository**: Start by forking this repository to your account.
2. **Develop Your Component**: Create your Viash component, ensuring it aligns with our best practices (detailed below).
3. **Submit a Pull Request**: After testing your component, submit a pull request for review.

## Contribution Guidelines

```{r echo=FALSE}
lines <- readr::read_lines("CONTRIBUTING.md")

index_start <- grep("^### ", lines)

index_end <- c(index_start[-1] - 1, length(lines))

name <- gsub("^## ", "", lines[index_start])
description <- lines[index_start + 2]

knitr::asis_output(
  paste(paste0(" * **", name, "**: ", description, "\n"), collapse = "")
)
```

See the [CONTRIBUTING](CONTRIBUTING.md) file for more details.


## Support and Community

For support, questions, or to join our community:

- **Issues**: Submit questions or issues via the [GitHub issue tracker](https://github.com/viash-hub/base/issues).
- **Discussions**: Join our discussions via [GitHub Discussions](https://github.com/viash-hub/base/discussions).

## License
This repository is licensed under an MIT license. See the [LICENSE](LICENSE) file for details.
