#!/bin/bash

## VIASH START
## VIASH END

set -e

test_output_dir="${meta_resources_dir}test_data/test_output"
test_dir="${meta_resources_dir}test_data"
expected_output_dir="${meta_resources_dir}test_data/output"

mkdir -p "$test_output_dir"


################################################################################

echo "> Test 1 - Read annotation file, output GFF" 

"$meta_executable" \
  --expose_dups \
  --input "$test_dir/annotation.gff" \
  -o "$test_output_dir/ann_simple.gff" 

echo ">> Check if output exists"
[ ! -f "$test_output_dir/ann_simple.gff" ] \
    && echo "Output file test_output/ann_simple.gff does not exist" && exit 1

echo ">> Check if output is empty"
[ ! -s "$test_output_dir/ann_simple.gff" ] \
    && echo "Output file test_output/ann_simple.gff is empty" && exit 1

echo ">> Compare output to expected output"

# Not comparing header lines as they are not in the same order 
# (reference file was created with gffred version 11.8 instead of 12.7).
diff <(grep -v '^#' "$expected_output_dir/ann_simple.gff") \
    <(grep -v '^#' "$test_output_dir/ann_simple.gff") || \
    (echo "Output file ann_simple.gff does not match expected output" && exit 1)


################################################################################

echo "> Test 2 - Read annotation file, output GTF"

"$meta_executable" \
  --gtf_output \
  --outfile "$test_output_dir/annotation.gtf" \
  --input "$test_dir/annotation.gff"

echo ">> Check if output exists"
[ ! -f "$test_output_dir/annotation.gtf" ] \
    && echo "Output file test_output/annotation.gtf does not exist" && exit 1

echo ">> Check if output is empty"
[ ! -s "$test_output_dir/annotation.gtf" ] \
    && echo "Output file test_output/annotation.gtf is empty" && exit 1

echo ">> Compare output to expected output"

# removing trailing semicolons from the files
# Difference in trailing semicolon presence possibly due to reference output 
# being generated by gffred version 11.8 instead of 12.7.
sed -i 's/;$/''/' "$expected_output_dir/annotation.gtf"
sed -i 's/;$/''/' "$test_output_dir/annotation.gtf"

diff "$expected_output_dir/annotation.gtf" "$test_output_dir/annotation.gtf" || \
    (echo "Output file annotation.gtf does not match expected output" && exit 1)

################################################################################

echo "> Test 3 - Generate fasta file from annotation file"


"$meta_executable" \
  --genome "$test_dir/genome.fa" \
  --spliced_exons "$test_output_dir/transcripts.fa" \
  --input "$test_dir/annotation.gff"

echo ">> Check if output exists"
[ ! -f "$test_output_dir/transcripts.fa" ] \
    && echo "Output file transcripts.fa does not exist" && exit 1

echo ">> Check if output is empty"
[ ! -s "$test_output_dir/transcripts.fa" ] \
    && echo "Output file transcripts.fa is empty" && exit 1

echo ">> Compare output to expected output"
diff "$expected_output_dir/transcripts.fa" "$test_output_dir/transcripts.fa" || \
    (echo "Output file transcripts.fa does not match expected output" && exit 1)

################################################################################

echo "> Test 4 - Generate table from GFF annotation file"

# reference output annotation.tbl was created manually with gffread 0.12.7

"$meta_executable" \
  --table @id,@chr,@start,@end,@strand,@exons,Name,gene,product \
  --outfile "$test_output_dir/annotation.tbl" \
  --input "$test_dir/annotation.gff"

echo ">> Check if output exists"
[ ! -f "$test_output_dir/annotation.tbl" ] \
    && echo "Output file test_output/annotation.tbl does not exist" && exit 1

echo ">> Check if output is empty"
[ ! -s "$test_output_dir/annotation.tbl" ] \
    && echo "Output file test_output/annotation.tbl is empty" && exit 1

echo ">> Compare output to expected output"
diff "$expected_output_dir/annotation.tbl" "$test_output_dir/annotation.tbl" || \
    (echo "Output file annotation.tbl does not match expected output" && exit 1)

################################################################################

rm -r "$test_output_dir"

echo "> All tests successful"

exit 0