name: agat_convert_mfannot2gff
namespace: agat
description: |
  Conversion utility for MFannot "masterfile" annotation produced by the
  [MFannot pipeline](http://megasun.bch.umontreal.ca/RNAweasel/). Reports
  GFF3 format.
keywords: [gene annotations, GFF , Mfannot]
links:
  homepage: https://github.com/NBISweden/AGAT
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_convert_mfannot2gff.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references: 
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  commands: ["agat_convert_mfannot2gff.pl"]
authors:
  - __merge__: /src/_authors/leila_paquay.yaml
    roles: [ author, maintainer ]
argument_groups:
  - name: Inputs
    arguments:
      - name: --mfannot
        alternatives: [-m, -i]
        description: The mfannot input file.
        type: file
        required: true
        direction: input
        example: input.mfannot
  - name: Outputs
    arguments:
      - name: --gff
        alternatives: [-g, -o]
        description: The GFF output file.
        type: file
        direction: output
        required: true
        example: output.gff
  - name: Arguments
    arguments:
      - name: --config
        alternatives: [-c]
        description: |
          AGAT config file. By default AGAT takes the original agat_config.yaml shipped with AGAT. The `--config` option gives you the possibility to use your own AGAT config file (located elsewhere or named differently).
        type: file
        required: false
        example: custom_agat_config.yaml
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: test_data
engines:
  - type: docker
    image: quay.io/biocontainers/agat:1.4.0--pl5321hdfd78af_0
    setup:
      - type: docker
        run: |
          agat --version | sed 's/AGAT\s\(.*\)/agat: "\1"/' > /var/software_versions.txt
runners:
  - type: executable
  - type: nextflow